export const public_primevue_provider_adapter = {
  providerId: "public-primevue",
  deliveryEntryId: "vue3-public-primevue",
  providerThemeAdapterId: "public-primevue-theme-bridge",
  componentLibraryPackages: [
    "primevue",
    "@primeuix/themes",
  ],
  mappedComponents: {
    UiButton: "Button",
    UiInput: "InputText",
    UiSelect: "Select",
    UiForm: "Fieldset",
    UiFormItem: "FloatLabel",
    UiTable: "DataTable",
    UiDialog: "Dialog",
    UiDrawer: "Drawer",
    UiEmpty: "Message",
    UiSpinner: "ProgressSpinner",
    UiPageHeader: "Toolbar",
    UiTabs: "Tabs",
    UiSearchBar: "InputGroup",
    UiFilterBar: "Toolbar",
    UiResult: "Message",
    UiSection: "Panel",
    UiToolbar: "Toolbar",
    UiPagination: "Paginator",
    UiCard: "Card",
  },
  whitelistComponentIds: [
    "UiButton",
    "UiInput",
    "UiSelect",
    "UiForm",
    "UiFormItem",
    "UiTable",
    "UiDialog",
    "UiDrawer",
    "UiEmpty",
    "UiSpinner",
    "UiPageHeader",
    "UiTabs",
    "UiSearchBar",
    "UiFilterBar",
    "UiResult",
    "UiSection",
    "UiToolbar",
    "UiPagination",
    "UiCard",
  ],
  relativePath: "src/frontend-governance/runtime/providers/public-primevue/ProviderAdapter.tsx",
} as const;
